name: ci 
on:
  push:
    branches:
      - trunk
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: 3.x

      - run: pip install mkdocs-material 
        name: Install MkDocs Material

      - run: mkdocs gh-deploy --force --remote-branch main
        name: Build and Deploy
